[build]
command = "pnpm build:netlify"
publish = ".netlify"
edge_functions = ".netlify/functions"
[functions]
  directory = ".netlify/functions"
    [[redirects]]
      from = "https://proxy-12266matt.netlify.app/"
      to = "https://pstream.mov"
      status = 301
